In [2]:
import pandas as pd
import duckdb as dd

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

# Análise do Cenário 2

**O Contexto:** Na próxima semana, haverá uma audiência pública decisiva na Assembleia Legislativa para discutir a alocação de recursos do estado para o ano que vem. O governo está pedindo a aprovação de um pacote extra para iniciar novas obras de infraestrutura.

**O Problema:** A nossa equipe de auditoria do Observatório Social extraiu os dados do Portal da Transparência e suspeita que o problema não é falta de dinheiro, mas ineficiência e desperdício. Há indícios de que dezenas de projetos estão paralisados há anos, consumindo milhões em "aditivos contratuais" sucessivos sem que a população veja o resultado.

**A Missão da sua Equipe:** Os deputados, a imprensa e a população não têm paciência (nem letramento em dados) para olhar tabelas com milhares de contratos. A sua equipe precisa analisar a base de dados abertos, encontrar exatamente onde está o maior "ralo" de dinheiro público (Em qual secretaria? Em qual região?) e montar um pitch visual de 90 segundos. O objetivo é convencer os deputados a bloquearem o orçamento de novas obras até que uma "Força-Tarefa" resolva o gargalo principal que vocês identificarem.

O que vocês devem entregar:

* O insight da denúncia
* A evidência em dados
* A chamada para ação

## Dados para a atividade

**Atenção:** Os dados listados a seguir são fictícios e não representam cenários reais. Os dados foram criados a partir da IA para simular cenários práticos e que possuem uma abordagem didática para tratar de temas da disciplina. Não é possível fazer suposição sobre a realidade atual do estado.

In [4]:
FILE_CENARIO2 = "https://raw.githubusercontent.com/adolfoguimaraes/curso-dataviz/refs/heads/main/dataset/obras_publicas_se_2022_2026.csv"
data_ = pd.read_csv(FILE_CENARIO2)
data_

,id_contrato,municipio_execucao,secretaria_responsavel,status_obra,orcamento_inicial_reais,valor_aditivos_reais,dias_de_atraso,percentual_conclusao
0,CT-2022-0001,Aracaju,Infraestrutura,Concluída,2130399.63,228051.44,0,100.0
1,CT-2022-0002,Tobias Barreto,Segurança,Concluída,2270898.17,0.00,0,100.0
2,CT-2022-0003,Estância,Segurança,Paralisada,833916.61,271908.70,194,19.4
3,CT-2022-0004,Estância,Educação,Concluída,737476.91,76876.60,0,100.0
4,CT-2022-0005,Barra dos Coqueiros,Saúde,Paralisada,357872.43,916186.70,1149,16.6
...,...,...,...,...,...,...,...,...
8195,CT-2022-8196,São Cristóvão,Segurança,Atrasada,605155.53,234906.45,331,50.7
8196,CT-2022-8197,Aracaju,Cultura e Esporte,Em Andamento,12640141.06,0.00,0,23.3
8197,CT-2022-8198,Aracaju,Educação,Paralisada,1999047.58,841625.45,600,71.8
8198,CT-2022-8199,Nossa Senhora do Socorro,Infraestrutura,Em Andamento,693834.35,0.00,0,37.2
8199,CT-2022-8200,Lagarto,Segurança,Concluída,1076672.64,132965.79,0,100.0

**Opção 1:** Python com Pandas

In [5]:
data_ = pd.read_csv(FILE_CENARIO2)
data_

,id_contrato,municipio_execucao,secretaria_responsavel,status_obra,orcamento_inicial_reais,valor_aditivos_reais,dias_de_atraso,percentual_conclusao
0,CT-2022-0001,Aracaju,Infraestrutura,Concluída,2130399.63,228051.44,0,100.0
1,CT-2022-0002,Tobias Barreto,Segurança,Concluída,2270898.17,0.00,0,100.0
2,CT-2022-0003,Estância,Segurança,Paralisada,833916.61,271908.70,194,19.4
3,CT-2022-0004,Estância,Educação,Concluída,737476.91,76876.60,0,100.0
4,CT-2022-0005,Barra dos Coqueiros,Saúde,Paralisada,357872.43,916186.70,1149,16.6
...,...,...,...,...,...,...,...,...
8195,CT-2022-8196,São Cristóvão,Segurança,Atrasada,605155.53,234906.45,331,50.7
8196,CT-2022-8197,Aracaju,Cultura e Esporte,Em Andamento,12640141.06,0.00,0,23.3
8197,CT-2022-8198,Aracaju,Educação,Paralisada,1999047.58,841625.45,600,71.8
8198,CT-2022-8199,Nossa Senhora do Socorro,Infraestrutura,Em Andamento,693834.35,0.00,0,37.2
8199,CT-2022-8200,Lagarto,Segurança,Concluída,1076672.64,132965.79,0,100.0

**Opção 2** Usando o SQL com o DuckerDB.

In [7]:
query = """
SELECT *
FROM data_
WHERE status_obra = 'Paralisada'
LIMIT 10
"""

display(dd.sql(query).df())

,id_contrato,municipio_execucao,secretaria_responsavel,status_obra,orcamento_inicial_reais,valor_aditivos_reais,dias_de_atraso,percentual_conclusao
0,CT-2022-0003,Estância,Segurança,Paralisada,833916.61,271908.70,194,19.4
1,CT-2022-0005,Barra dos Coqueiros,Saúde,Paralisada,357872.43,916186.70,1149,16.6
2,CT-2022-0011,Barra dos Coqueiros,Saúde,Paralisada,1724060.92,5557783.31,1483,37.6
3,CT-2022-0015,Itabaiana,Saúde,Paralisada,872082.01,134722.16,417,67.4
4,CT-2022-0016,Aracaju,Saúde,Paralisada,4249363.40,11948222.18,1399,20.5
5,CT-2022-0020,Nossa Senhora do Socorro,Saúde,Paralisada,8441619.94,24141634.61,1670,35.1
6,CT-2022-0024,Aracaju,Segurança,Paralisada,5129127.50,634175.17,766,40.6
7,CT-2022-0025,Barra dos Coqueiros,Saúde,Paralisada,1928572.06,3909146.15,1745,15.7
8,CT-2022-0029,Nossa Senhora do Socorro,Saúde,Paralisada,315336.57,915276.45,1208,33.2
9,CT-2022-0033,Aracaju,Infraestrutura,Paralisada,1537908.49,739525.68,327,59.8